### ISSUE TITLE
Latest openpilot's supercombo.onnx does not compile

### ISSUE THREAD

**Issue by haraschax** [tinygrad/tinygrad#1926]
The latest openpilot driving model contains attention layers since:
https://github.com/commaai/openpilot/commit/3799fe46b3a629e491d4b8498b8ae83e4c88c304

To reproduce you can run
```
curl -L -o /tmp/supercombo.onnx https://github.com/commaai/openpilot/raw/3799fe46b3a629e491d4b8498b8ae83e4c88c304/selfdrive/modeld/models/supercombo.onnx

NATIVE_EXPLOG=1 VALIDHACKS=1 OPTLOCAL=1 IMAGE=2 GPU=1 ENABLE_METHOD_CACHE=1 python3 openpilot/compile.py /tmp/supercombo.onnx /tmp/supercombo.thneed
```

which produces
```
NATIVE_EXPLOG=1 VALIDHACKS=1 OPTLOCAL=1 IMAGE=2 GPU=1 ENABLE_METHOD
_CACHE=1 python3 openpilot/compile.py /tmp/supercombo.onnx /tmp/supercombo.thneed     
realizing                                                                                                                  
Traceback (most recent call last):                                                                                         
  File "/home/batman/xx/openpilot/tinygrad_repo/openpilot/compile.py", line 151, in <module>
    compile(dat, sys.argv[2])                                                                                              
  File "/home/batman/xx/openpilot/tinygrad_repo/openpilot/compile.py", line 59, in compile
    for i in range(2): tinygrad_out = model_exec(run_onnx, i == 1 and using_graph, **inputs)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/jit.py", line 66, in __call__             
    self.ret = self.fxn(*args, **kwargs)                                                                                   
               ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                   
  File "/home/batman/xx/openpilot/tinygrad_repo/openpilot/compile.py", line 45, in model_exec
    return ret.realize()                                                                                                   
           ^^^^^^^^^^^^^                                                                                                   
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/tensor.py", line 87, in realize
    self.lazydata.realize()                                                                                                
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/lazy.py", line 151, in realize                                    
    for x in self.op.buffers: x.realize()                                                                                  
                              ^^^^^^^^^^^                                                                                  
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/lazy.py", line 138, in realize            
    elif self.optype is MovementOps: self.realized = self.op.src[0].realize().realized 
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^         
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/lazy.py", line 138, in realize
    elif self.optype is MovementOps: self.realized = self.op.src[0].realize().realized 
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^         

......

File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/lazy.py", line 138, in realize                                    
    elif self.optype is MovementOps: self.realized = self.op.src[0].realize().realized 
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^                                              
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/lazy.py", line 154, in realize                                    
    self.realized = Device[self.device].exec_ast(op, output=self, inputs=realized_bufs, var_vals=self.var_vals, **self._device_extra_args())                                                                                                          
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/ops.py", line 256, in exec_ast
    prg.exec([output.realized]+inputs, var_vals=var_vals)                                                                  
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/ops.py", line 180, in exec    
    return self(rawbufs, var_vals, force_wait=force_wait)                                                                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                  
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/ops.py", line 190, in __call__
    if et := self.clprg(global_size, local_size, *rawbufs, *var_vals.values(), wait=force_wait or DEBUG>=1): GlobalCounters.time_sum_s += et                                                                                                          
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                
  File "/home/batman/xx/openpilot/tinygrad_repo/tinygrad/runtime/ops_gpu.py", line 97, in __call__                         
    e = self.clprgs[cl_bufs[0].device](CL.cl_queue[cl_bufs[0].device], [g*l for g,l in zip(global_size, local_size)] if local_size is not None else global_size, local_size, *cl_bufs, wait_for=wait_for)                                             
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                             
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/__init__.py", line 900, in kernel_call   
    return self._enqueue(self, queue, global_size, local_size, *args, **kwargs)                                            
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                            
  File "<pyopencl invoker for 'E_5_3_2_8_4'>", line 9, in enqueue_knl_E_5_3_2_8_4                                          
pyopencl._cl.LogicError: clSetKernelArg failed: INVALID_MEM_OBJECT - when processing arg#1 (1-based):      

```

**Comment by geohot** [comment]
Reproduced, looking into it.

**Comment by geohot** [comment]
Should be fixed on this branch:

https://github.com/tinygrad/tinygrad/tree/op_fix_hacks

It's not a clean fix, these image dtypes are really annoying.

**Comment by haraschax** [comment]
Great, confirmed that branch works. I'd like to update tinygrad in openpilot, but probably still can't with that branch. Still 10-20% slower than tinygrad 0.5. And the FastViT model we are trying to ship soon is at the limit of what we can run on device. With a 20% slowdown it can't run realtime on a C3 anymore.

https://github.com/commaai/openpilot/pull/30077

**Comment by geohot** [comment]
This will fix it in a sustainable way. https://github.com/tinygrad/tinygrad/pull/1976

fastvit is giving the wrong answer though, looking into it
